More stabbing at propagating signals; fix mounting src at /usr/local/selby

diff --git a/bin/gqc b/bin/gqc
--- a/bin/gqc
+++ b/bin/gqc
@@ -16,9 +16,10 @@ GQC_DEBUG=$(echo "${GQC_DEBUG}" | tr A-Z a-z)
 if [[ "${GQC_DEBUG}" == "true" ]]; then set -xv; fi
 export GQC_DEV="${GQC_DEV:-false}"
 GQC_DEV=$(echo "${GQC_DEV}" | tr A-Z a-z)
+GQC_PID=$$
 
 prg=${BASH_SOURCE[0]}
-([[ -n "${prg}" ]] && [[ -f "${prg}" ]]) || (echo "[FATAL] cannot locate: '$0'" 1>&2; exit 1)
+([[ -n "${prg}" ]] && [[ -f "${prg}" ]]) || (echo "[FATAL] cannot locate: '$0'" 1>&2; kill -USR2 $GQC_PID)
 task=$(basename -- "$0")
 taskdir=$(cd $(dirname -- "$0")/.. > /dev/null && pwd)
 
@@ -54,13 +55,13 @@ function gqcw.main() {
         case ${1} in
         -C|--cache-directory)
             local file="${2}" && shift
-            ([[ -d "${file}" ]] && [[ -w "${file}" ]]) || (echo "[FATAL] cache directory does not exist or can not be written: '${file}'" 1>&2; exit 1)
+            ([[ -d "${file}" ]] && [[ -w "${file}" ]]) || (echo "[FATAL] cache directory does not exist or can not be written: '${file}'" 1>&2; kill -USR2 $GQC_PID)
             cachedir="${file}"
             ;;
         -L|--log-file)
             local file="${2}" && shift
-            [[ -e "${file}" ]] || (touch -- "${file}" || echo "[FATAL] log file can not be written: '${file}'" 1>&2; exit 1)
-            [[ -w "${file}" ]] || (echo "[FATAL] log file can not be written: '${file}'" 1>&2; exit 1)
+            [[ -e "${file}" ]] || (touch -- "${file}" || echo "[FATAL] log file can not be written: '${file}'" 1>&2; kill -USR2 $GQC_PID)
+            [[ -w "${file}" ]] || (echo "[FATAL] log file can not be written: '${file}'" 1>&2; kill -USR2 $GQC_PID)
             logfile="${file}"
             ;;
         --Xcontainer-name)
@@ -120,7 +121,7 @@ function gqcw.main() {
              cat "${tmp}" | while read line ; do
                  echo "[DEBUG] ${line}'" 1>&2
              done
-             exit 1
+             kill -USR2 $GQC_PID
          fi
         echo "[INFO] image build complete: '${Ximage}' ..."
     fi
@@ -161,11 +162,13 @@ function gqcw.main() {
     fi
 }
 
-trap 's=$?; rm -r ${TMPDIR}/${task}-${$}; exit $s' HUP INT TERM
+trap 'exit 0' USR1
+trap 'exit 1' USR2
+trap 's=$?; rm -rf ${TMPDIR}/${task}-${$}; exit $s' HUP INT TERM EXIT
 (
     gqcw.main "$@"
 )
-trap - HUP INT TERM EXIT
+trap - HUP INT TERM EXIT USR1 USR2
 exit 0
 
 
