Skip record if "selbyNumber" field is not a decimal integer

diff --git a/src/bin/gqc b/src/bin/gqc
--- a/src/bin/gqc
+++ b/src/bin/gqc
@@ -142,7 +142,7 @@ function cache.get-meta-filename() {
 
 function cache.get() {
     local key="${1:?Need key}"
-    cache.__get "${key}" || (error "Key «$key» data file '$(cache.get-data-filename \"${key}\")' can not be read" 1>&2 ; exit 1)
+    cache.__get "${key}" || (log.error "Key «$key» data file '$(cache.get-data-filename \"${key}\")' can not be read" 1>&2 ; exit 1)
 }
 
 function cache.get-metadata() {
@@ -493,8 +493,8 @@ function gqc.main() {
 
     cat "${GQC[INPUT]}" | text.trim | while read country state selbyNumber latitude longitude ; do
         log.debug "raw-record: country='${country}' state='${state}' selbyNumber='${selbyNumber}' latitude='${latitude}' longitude='${longitude}'"
-
-        (echo "${country}" | text.trim | grep -q '^#') && continue # Skip comment lines
+        (echo "${country}" | text.trim | grep -q -E '^\s*#') && continue # Skip comment lines
+        (echo "${selbyNumber}" | grep -q -E -v '^[[:digit:]]+$') && continue # Skip if selbyNumber is not a decimal number
         local c_country=$(text.canonicalize "${country}")
         local c_state=$(text.canonicalize "${state}")
         local c_latitude=$(gqc.clean-latitude "${latitude}")
@@ -502,25 +502,29 @@ function gqc.main() {
         log.debug "cleaned: c_country='${c_country}' c_state='${c_state}' selbyNumber='${selbyNumber}' c_latitude='${c_latitude}' c_longitude='${c_longitude}'"
         local response=$(gqc.reverse-geolocate ${c_latitude} ${c_longitude})
         log.debug "[lat=${c_latitude}, lon=${c_longitude}] => ${response}"
-        local r_country=$(echo "${response}" | jq .address.country | tr -d '"')
-        local r_country_code=$(echo "${response}" | jq .address.country_code | tr -d '"')
-        local r_state=$(echo "${response}" | jq .address.state | tr -d '"')
-        local r_county=$(echo "${response}" | jq .address.county | tr -d '"')
-        local r_city=$(echo "${response}" | jq .address.city | tr -d '"')
-        local r_region=$(echo "${response}" | jq .address.region | tr -d '"')
-        local r_display_name=$(echo "${response}" | jq .display_name | tr -d '"')
-        local c_r_country=$(text.canonicalize "${r_country}")
-        local c_r_country_code=$(text.canonicalize "${r_country_code}")
-        local c_r_state=$(text.canonicalize "${r_state}")
-        local c_r_county=$(text.canonicalize "${r_county}")
-        local c_r_city=$(text.canonicalize "${r_city}")
-        local c_r_region=$(text.canonicalize "${r_region}")
-
-        log.info "Reverse geoCode: {sn=$selbyNumber, country=\"$country\", div1=\"${state}\", lat=$latitude, lon=$longitude} => {country=\"$r_country\", state=\"$r_state\", response=${response}}}"
-        if [[ "${c_r_country}" != "${c_country}" ]]; then
-            log.error "SN-${selbyNumber}: country '${country}' != reverse geocode '${r_country}'"
-        elif [[ "${c_r_state}" != "${c_state}" ]]; then
-            log.error "SN-${selbyNumber}: div1 '${state}' != reverse geocode '${r_state}'"
+        if [[ -z "${response}" ]]; then
+            log.warn "reverse-geolocate ${c_latitude} ${c_longitude} failed"
+        else
+            local r_country=$(echo "${response}" | jq .address.country | tr -d '"')
+            local r_country_code=$(echo "${response}" | jq .address.country_code | tr -d '"')
+            local r_state=$(echo "${response}" | jq .address.state | tr -d '"')
+            local r_county=$(echo "${response}" | jq .address.county | tr -d '"')
+            local r_city=$(echo "${response}" | jq .address.city | tr -d '"')
+            local r_region=$(echo "${response}" | jq .address.region | tr -d '"')
+            local r_display_name=$(echo "${response}" | jq .display_name | tr -d '"')
+            local c_r_country=$(text.canonicalize "${r_country}")
+            local c_r_country_code=$(text.canonicalize "${r_country_code}")
+            local c_r_state=$(text.canonicalize "${r_state}")
+            local c_r_county=$(text.canonicalize "${r_county}")
+            local c_r_city=$(text.canonicalize "${r_city}")
+            local c_r_region=$(text.canonicalize "${r_region}")
+    
+            log.info "reverse-geoCode: {sn=$selbyNumber, country=\"$country\", div1=\"${state}\", lat=$latitude, lon=$longitude} => {country=\"$r_country\", state=\"$r_state\", response=${response}}}"
+            if [[ "${c_r_country}" != "${c_country}" ]]; then
+                log.error "SN-${selbyNumber}: country '${country}' != reverse geocode '${r_country}'"
+            elif [[ "${c_r_state}" != "${c_state}" ]]; then
+                log.error "SN-${selbyNumber}: div1 '${state}' != reverse geocode '${r_state}'"
+            fi
         fi
 
         # TODO - Add a start and end record number to process; syntactic sugar for piping the dataset through head and tail.
@@ -535,12 +539,11 @@ function gqc.reverse-geolocate() {
     local longitude=$(text.trim "${2:?Need longitude}")
     local usecache="${3:-true}"
     local cachekey="latitude:${latitude},longitude:${longitude}"
-    if [[ "${usecache}" == 'true' ]] && cache.__get "${cachekey}"; then
-        # get writes the record to stdout, so nothing to do here
-        true
+    if [[ "${usecache}" == 'true' ]] && cache.exists "${cachekey}"; then
+        cache.get "${cachekey}"
     else
         result=$(locationiq.reverse-geolocate ${latitude} ${longitude})
-        cache.put "${cachekey}" "${result}"
+        [[ -n "${result}" ]] && cache.put "${cachekey}" "${result}"
         echo "${result}"
     fi
 }
